/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package semeando_futuro.view;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import semeando_futuro.dao.AlunoDAO;
import semeando_futuro.dao.FestaDAO;
import semeando_futuro.dao.PresencaDAO;
import semeando_futuro.modelo.Aluno;
import semeando_futuro.modelo.Calendario;
import semeando_futuro.modelo.Festa;
import semeando_futuro.modelo.Presenca;

/**
 *
 * @author lab
 */
public class IFrm_Festa extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrm_Chamada
     */
    public IFrm_Festa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txt_NomeCad = new javax.swing.JTextField();
        txt_DataCad = new com.toedter.calendar.JDateChooser();
        txt_pagamentoCad = new javax.swing.JFormattedTextField();
        jLabel43 = new javax.swing.JLabel();
        btn_novo = new javax.swing.JButton();
        btn_cad = new javax.swing.JButton();
        txt_RAALUNOCAD = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ObsCad = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        cb_pes = new javax.swing.JComboBox();
        txt_pes = new javax.swing.JTextField();
        btn_pes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_festa = new javax.swing.JTable();
        btn_alterar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txt_RAAlunoCons = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txt_datacons = new com.toedter.calendar.JDateChooser();
        txt_pagamentocons = new javax.swing.JFormattedTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        txt_NomeCons = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_obsCons = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        btn_novo2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_ate1 = new com.toedter.calendar.JDateChooser();
        jLabel24 = new javax.swing.JLabel();
        txt_de1 = new com.toedter.calendar.JDateChooser();
        btn_novo4 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btn_novo5 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txt_de3 = new com.toedter.calendar.JDateChooser();
        txt_ate3 = new com.toedter.calendar.JDateChooser();
        jLabel38 = new javax.swing.JLabel();
        btn_novo8 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        txt_RA2 = new javax.swing.JTextField();
        txt_RA1 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Festas");

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(1, 108, 78));
        jLabel10.setText("RA do Aluno:");

        jLabel40.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(1, 108, 78));
        jLabel40.setText("Pagamento:");

        jLabel41.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(1, 108, 78));
        jLabel41.setText("Nome do Festa:");

        jLabel42.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(1, 108, 78));
        jLabel42.setText("Data da festa :");

        try {
            txt_pagamentoCad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$####,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel43.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(1, 108, 78));
        jLabel43.setText("Observação:");

        btn_novo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_novo.setForeground(new java.awt.Color(0, 102, 102));
        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_cad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_cad.setForeground(new java.awt.Color(0, 102, 102));
        btn_cad.setText("Cadastrar");
        btn_cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadActionPerformed(evt);
            }
        });

        txt_ObsCad.setColumns(20);
        txt_ObsCad.setRows(5);
        jScrollPane2.setViewportView(txt_ObsCad);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel10)
                .addGap(65, 65, 65)
                .addComponent(jLabel41))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(txt_RAALUNOCAD, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(txt_NomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel42)
                .addGap(97, 97, 97)
                .addComponent(jLabel40))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(txt_DataCad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(txt_pagamentoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel43))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btn_cad, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel41))
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_RAALUNOCAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(jLabel40))
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_DataCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pagamentoCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel43)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Cadastro", jPanel6);

        cb_pes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RA", "Data" }));

        txt_pes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pesKeyPressed(evt);
            }
        });

        btn_pes.setText("Pesquisar");
        btn_pes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesActionPerformed(evt);
            }
        });

        tbl_festa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "idFesta", "RA do Aluno", "Nome da Festa", "Data da Festa", "Pagamento", "Obs"
            }
        ));
        tbl_festa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_festaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_festa);

        btn_alterar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_alterar.setForeground(new java.awt.Color(0, 102, 102));
        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_excluir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_excluir.setForeground(new java.awt.Color(0, 102, 102));
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(1, 108, 78));
        jLabel11.setText("RA do Aluno:");

        jLabel44.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(1, 108, 78));
        jLabel44.setText("Nome do Festa:");

        jLabel45.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(1, 108, 78));
        jLabel45.setText("Data da festa :");

        try {
            txt_pagamentocons.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$####,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel46.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(1, 108, 78));
        jLabel46.setText("Pagamento:");

        jLabel47.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(1, 108, 78));
        jLabel47.setText("Observação:");

        jLabel48.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(1, 108, 78));
        jLabel48.setText("id:");

        lbl_id.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(1, 108, 78));
        lbl_id.setText("----");

        txt_obsCons.setColumns(20);
        txt_obsCons.setRows(5);
        jScrollPane3.setViewportView(txt_obsCons);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(cb_pes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txt_pes, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btn_pes))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel48)
                .addGap(56, 56, 56)
                .addComponent(jLabel11)
                .addGap(55, 55, 55)
                .addComponent(jLabel44))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txt_RAAlunoCons, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txt_NomeCons, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel45)
                .addGap(47, 47, 47)
                .addComponent(jLabel46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(txt_datacons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(txt_pagamentocons, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel47))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_pes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pes))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel48)
                    .addComponent(jLabel11)
                    .addComponent(jLabel44))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_id)
                    .addComponent(txt_RAAlunoCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NomeCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45)
                    .addComponent(jLabel46))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_datacons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pagamentocons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel47)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Consulta", jPanel1);

        jLabel21.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(1, 108, 78));
        jLabel21.setText("Até:");

        btn_novo2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_novo2.setForeground(new java.awt.Color(0, 102, 102));
        btn_novo2.setText("Gerar");
        btn_novo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo2ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(1, 108, 78));
        jLabel22.setText("Relatório Completo:");

        jLabel23.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(1, 108, 78));
        jLabel23.setText("Relatório por Aluno:");

        jLabel24.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(1, 108, 78));
        jLabel24.setText("De:");

        btn_novo4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_novo4.setForeground(new java.awt.Color(0, 102, 102));
        btn_novo4.setText("Gerar");
        btn_novo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo4ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(1, 108, 78));
        jLabel25.setText("Relatório por data:");

        jLabel26.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(1, 108, 78));
        jLabel26.setText("RA do aluno:");

        btn_novo5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_novo5.setForeground(new java.awt.Color(0, 102, 102));
        btn_novo5.setText("Gerar");
        btn_novo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo5ActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(1, 108, 78));
        jLabel34.setText("Relatório por Aluno");

        jLabel35.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(1, 108, 78));
        jLabel35.setText("e Data");

        jLabel37.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(1, 108, 78));
        jLabel37.setText("De:");

        jLabel38.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(1, 108, 78));
        jLabel38.setText("Até:");

        btn_novo8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_novo8.setForeground(new java.awt.Color(0, 102, 102));
        btn_novo8.setText("Gerar");
        btn_novo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo8ActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(1, 108, 78));
        jLabel39.setText("RA do aluno:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(16, 16, 16)
                        .addComponent(btn_novo4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(txt_de1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(txt_ate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(btn_novo5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_RA1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btn_novo2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel39)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel37)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel38))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(93, 93, 93)
                        .addComponent(txt_RA2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txt_de3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(txt_ate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(btn_novo8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel22))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btn_novo4)))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(5, 5, 5)
                        .addComponent(txt_de1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(5, 5, 5)
                        .addComponent(txt_ate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btn_novo5)))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(5, 5, 5)
                        .addComponent(txt_RA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btn_novo2)))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_RA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_de3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_novo8))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Relatórios", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Cadastro de Chamada");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadActionPerformed
        
        Festa a = new Festa();

        if (txt_DataCad.getDate()==null) {
            JOptionPane.showMessageDialog(null, "Selecione a Data Corretamente");
        } else if (txt_NomeCad.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o nome da festa Corretamente");
        }else if (txt_pagamentoCad.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o valor Corretamente");
        } else {
            try {
                java.util.Date F = txt_DataCad.getDate();
                SimpleDateFormat format1 = new SimpleDateFormat("yyyy/MM/dd");
                String datachamada = format1.format(F);

                a.setRAAluno(txt_RAALUNOCAD.getText());
                a.setNome(txt_NomeCad.getText());
                a.setData_Festa(datachamada);
                a.setPagamento(Double.parseDouble(txt_pagamentoCad.getText().replace("R$", "").replace(",", ".")));
                a.setObservacao(txt_ObsCad.getText());
                
                
            } catch (Exception e) {

            }
            FestaDAO adao = new FestaDAO();
            adao.adciona(a);
            JOptionPane.showMessageDialog(null, "Festa Cadastrada com sucesso");
        }
    }//GEN-LAST:event_btn_cadActionPerformed

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed

    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_pesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesActionPerformed
        FestaDAO ldao = new FestaDAO();
        Festa l = new Festa();
        String campo=null;
        if(cb_pes.getSelectedIndex()==0){
            campo="Aluno.RA";
        }else if(cb_pes.getSelectedIndex()==1){
            campo="data_festa";
        }
        

        ldao.Consultar(campo, txt_pes.getText(), l);
             
    
        String r = l.getPagamento().toString();
        r.replace(".", "");
        
        lbl_id.setText(""+l.getId_Festa());
        txt_RAAlunoCons.setText(""+l.getRAAluno());
        txt_NomeCons.setText(""+l.getNome());
        txt_datacons.setDate(l.getDate());
        txt_obsCons.setText(""+l.getObservacao());
        txt_pagamentocons.setText(r);

        List<Festa> festas = ldao.getLista(campo, txt_pes.getText());
        DefaultTableModel model = (DefaultTableModel) tbl_festa.getModel();
        model.setNumRows(0);

        for (Festa festa : festas) {
            model.addRow(new Object[]{
                festa.getId_Festa(),
                festa.getRAAluno(),
                festa.getNome(),
                festa.getDate(),
                festa.getPagamento(),
                festa.getObservacao()});
        }
    }//GEN-LAST:event_btn_pesActionPerformed

    private void txt_pesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesKeyPressed
        btn_pesActionPerformed(null);
    }//GEN-LAST:event_txt_pesKeyPressed

    private void tbl_festaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_festaMouseClicked
        if (evt.getClickCount() == 1) {
            Integer y=0;
            FestaDAO ldao = new FestaDAO();
            txt_NomeCons.setText(tbl_festa.getValueAt(tbl_festa.getSelectedRow(), 2).toString());
            txt_RAAlunoCons.setText(tbl_festa.getValueAt(tbl_festa.getSelectedRow(), 1).toString());
            lbl_id.setText(tbl_festa.getValueAt(tbl_festa.getSelectedRow(), 0).toString());
            txt_datacons.setDate((Date) tbl_festa.getValueAt(tbl_festa.getSelectedRow(), 3));
            txt_pagamentocons.setText(tbl_festa.getValueAt(tbl_festa.getSelectedRow(), 4).toString().replace(".", ""));
            txt_obsCons.setText(tbl_festa.getValueAt(tbl_festa.getSelectedRow(), 5).toString());
        }
    }//GEN-LAST:event_tbl_festaMouseClicked

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        Festa a = new Festa();

        if (txt_datacons.getDate()==null) {
            JOptionPane.showMessageDialog(null, "Selecione a Data Corretamente");
        } else if (txt_NomeCons.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o nome da festa Corretamente");
        }else if (txt_pagamentocons.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o valor Corretamente");
        } else {
            try {
                java.util.Date F = txt_datacons.getDate();
                SimpleDateFormat format1 = new SimpleDateFormat("yyyy/MM/dd");
                String datachamada = format1.format(F);
                
                
                

                a.setRAAluno(txt_RAAlunoCons.getText());
                a.setNome(txt_NomeCons.getText());
                a.setData_Festa(datachamada);
                a.setPagamento(Double.parseDouble(txt_pagamentocons.getText().replace("R$", "").replace(",", ".")));
                a.setObservacao(txt_obsCons.getText());
                a.setId_Festa(Integer.parseInt(lbl_id.getText()));
                
                
            } catch (Exception e) {

            }
            FestaDAO adao = new FestaDAO();
            adao.Alterar(a);
            JOptionPane.showMessageDialog(null, "Festa Alterada com sucesso");
            btn_pesActionPerformed(evt);
        }
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        Festa p = new Festa();
        int r = JOptionPane.showConfirmDialog(null, "Deseja excluir esse registro");
        if (r == 0) {
            p.setId_Festa(Integer.parseInt(lbl_id.getText()));
            FestaDAO cdao = new FestaDAO();
            cdao.remove(p);
            JOptionPane.showMessageDialog(null, "Festa Removida com Sucesso");
            btn_pesActionPerformed(evt);
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_novo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo4ActionPerformed
        FestaDAO n = new FestaDAO();
        n.gerarRelCompleto();
    }//GEN-LAST:event_btn_novo4ActionPerformed

    private void btn_novo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo5ActionPerformed
        FestaDAO n = new FestaDAO();
        n.gerarRelData(txt_de1, txt_ate1);
    }//GEN-LAST:event_btn_novo5ActionPerformed

    private void btn_novo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo2ActionPerformed
        FestaDAO n = new FestaDAO();
        n.gerarRelRA(txt_RA1);
    }//GEN-LAST:event_btn_novo2ActionPerformed

    private void btn_novo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo8ActionPerformed
        FestaDAO n = new FestaDAO();
        n.gerarRelRAData(txt_RA2, txt_de3, txt_ate3);
        
    }//GEN-LAST:event_btn_novo8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_cad;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_novo2;
    private javax.swing.JButton btn_novo4;
    private javax.swing.JButton btn_novo5;
    private javax.swing.JButton btn_novo8;
    private javax.swing.JButton btn_pes;
    private javax.swing.JComboBox cb_pes;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JTable tbl_festa;
    private com.toedter.calendar.JDateChooser txt_DataCad;
    private javax.swing.JTextField txt_NomeCad;
    private javax.swing.JTextField txt_NomeCons;
    private javax.swing.JTextArea txt_ObsCad;
    private javax.swing.JTextField txt_RA1;
    private javax.swing.JTextField txt_RA2;
    private javax.swing.JTextField txt_RAALUNOCAD;
    private javax.swing.JTextField txt_RAAlunoCons;
    private com.toedter.calendar.JDateChooser txt_ate1;
    private com.toedter.calendar.JDateChooser txt_ate3;
    private com.toedter.calendar.JDateChooser txt_datacons;
    private com.toedter.calendar.JDateChooser txt_de1;
    private com.toedter.calendar.JDateChooser txt_de3;
    private javax.swing.JTextArea txt_obsCons;
    private javax.swing.JFormattedTextField txt_pagamentoCad;
    private javax.swing.JFormattedTextField txt_pagamentocons;
    private javax.swing.JTextField txt_pes;
    // End of variables declaration//GEN-END:variables
}
