/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package semeando_futuro.view;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import semeando_futuro.dao.PresencaDAO;
import semeando_futuro.dao.VisitaDAO;
import semeando_futuro.modelo.Presenca;
import semeando_futuro.modelo.Visita;

/**
 *
 * @author lab
 */
public class IFrm_Visita extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrm_Chamada
     */
    public IFrm_Visita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        btn_novo = new javax.swing.JButton();
        btn_cad = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txt_nomemaecad = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        txt_emailcad = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        txt_datacad = new com.toedter.calendar.JDateChooser();
        txt_nomepaicad = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_nomefilhocad = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        txt_telcad = new javax.swing.JFormattedTextField();
        jLabel49 = new javax.swing.JLabel();
        txt_celcad = new javax.swing.JFormattedTextField();
        jLabel50 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cb_pes = new javax.swing.JComboBox();
        txt_pes = new javax.swing.JTextField();
        btn_pes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_visita = new javax.swing.JTable();
        btn_alterar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        txt_nomemaecons = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txt_nomefilhocons = new javax.swing.JTextField();
        txt_nomepaicons = new javax.swing.JTextField();
        txt_datacans = new com.toedter.calendar.JDateChooser();
        jLabel41 = new javax.swing.JLabel();
        txt_emailcons = new javax.swing.JTextField();
        txt_telcons = new javax.swing.JFormattedTextField();
        jLabel55 = new javax.swing.JLabel();
        txt_celcons = new javax.swing.JFormattedTextField();
        jLabel56 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_ate1 = new com.toedter.calendar.JDateChooser();
        jLabel24 = new javax.swing.JLabel();
        txt_de1 = new com.toedter.calendar.JDateChooser();
        btn_novo4 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        btn_novo5 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Visitas");

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btn_novo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_novo.setForeground(new java.awt.Color(0, 102, 102));
        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_cad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_cad.setForeground(new java.awt.Color(0, 102, 102));
        btn_cad.setText("Cadastrar");
        btn_cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(1, 108, 78));
        jLabel19.setText("Nome Mãe:");

        jLabel51.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(1, 108, 78));
        jLabel51.setText("Email para contato:");

        jLabel52.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(1, 108, 78));
        jLabel52.setText("Data da visita:");

        jLabel20.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(1, 108, 78));
        jLabel20.setText("Nome Pai:");

        jLabel48.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(1, 108, 78));
        jLabel48.setText("Nome Filho(a):");

        try {
            txt_telcad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel49.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(1, 108, 78));
        jLabel49.setText("Fone Residencial:");

        try {
            txt_celcad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel50.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(1, 108, 78));
        jLabel50.setText("Celular:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel51)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel48)
                                .addComponent(txt_nomefilhocad, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(228, 228, 228))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btn_cad, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_nomemaecad, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel19))
                                    .addGap(26, 26, 26)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20)
                                        .addComponent(txt_nomepaicad, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel49)
                                        .addComponent(txt_telcad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel50)
                                        .addComponent(txt_celcad, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel52)
                                        .addComponent(txt_datacad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(txt_emailcad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_nomemaecad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addGap(5, 5, 5)
                        .addComponent(txt_nomepaicad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nomefilhocad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel49)
                            .addComponent(jLabel50))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_telcad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_celcad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel52)
                        .addGap(6, 6, 6)
                        .addComponent(txt_datacad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel51)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_emailcad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jPanel6);

        cb_pes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome Mãe", "Nome Pai", "Nome Filho", "Data Visita" }));

        txt_pes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pesKeyPressed(evt);
            }
        });

        btn_pes.setText("Pesquisar");
        btn_pes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesActionPerformed(evt);
            }
        });

        tbl_visita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "idVisita", "Nome Mãe", "Nome Pai", "Nome Filho(a)", "Telefone", "Celular", "Email", "Data da Visita"
            }
        ));
        tbl_visita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_visitaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_visita);
        if (tbl_visita.getColumnModel().getColumnCount() > 0) {
            tbl_visita.getColumnModel().getColumn(0).setMinWidth(60);
            tbl_visita.getColumnModel().getColumn(0).setPreferredWidth(60);
            tbl_visita.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        btn_alterar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_alterar.setForeground(new java.awt.Color(0, 102, 102));
        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_excluir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_excluir.setForeground(new java.awt.Color(0, 102, 102));
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        jLabel53.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(1, 108, 78));
        jLabel53.setText("Fone Residencial:");

        jLabel54.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(1, 108, 78));
        jLabel54.setText("Data da visita:");

        jLabel40.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(1, 108, 78));
        jLabel40.setText("Nome Pai:");

        jLabel41.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(1, 108, 78));
        jLabel41.setText("Nome Mãe:");

        try {
            txt_telcons.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel55.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(1, 108, 78));
        jLabel55.setText("Nome Filho (Aluno):");

        try {
            txt_celcons.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel56.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(1, 108, 78));
        jLabel56.setText("Email para contato:");

        jLabel42.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(1, 108, 78));
        jLabel42.setText("id:");

        lbl_id.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(1, 108, 78));
        lbl_id.setText("----");

        jLabel57.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(1, 108, 78));
        jLabel57.setText("Celular:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(cb_pes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txt_pes, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btn_pes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel42)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel41)
                        .addGap(162, 162, 162)
                        .addComponent(jLabel40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_nomemaecons, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(txt_nomepaicons, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(txt_nomefilhocons, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel53)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel57)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel54))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(txt_telcons, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_celcons, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_datacans, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel56))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(txt_emailcons, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_pes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pes))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(jLabel41)
                    .addComponent(jLabel40))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_id)
                    .addComponent(txt_nomemaecons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nomepaicons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel55)
                .addGap(6, 6, 6)
                .addComponent(txt_nomefilhocons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel54)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel53)
                            .addComponent(jLabel57))))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_telcons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_celcons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_datacans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel56)
                .addGap(6, 6, 6)
                .addComponent(txt_emailcons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Consulta", jPanel1);

        jLabel21.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(1, 108, 78));
        jLabel21.setText("Até:");

        jLabel22.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(1, 108, 78));
        jLabel22.setText("Relatório Completo:");

        jLabel24.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(1, 108, 78));
        jLabel24.setText("De:");

        btn_novo4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_novo4.setForeground(new java.awt.Color(0, 102, 102));
        btn_novo4.setText("Gerar");
        btn_novo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo4ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(1, 108, 78));
        jLabel25.setText("Relatório por data:");

        btn_novo5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_novo5.setForeground(new java.awt.Color(0, 102, 102));
        btn_novo5.setText("Gerar");
        btn_novo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(16, 16, 16)
                        .addComponent(btn_novo4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(txt_de1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(txt_ate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(btn_novo5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(btn_novo4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(5, 5, 5)
                        .addComponent(txt_de1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(5, 5, 5)
                        .addComponent(txt_ate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btn_novo5))))
        );

        jTabbedPane1.addTab("Relatórios", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Cadastro de Chamada");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadActionPerformed
        Visita a = new Visita();

        if (txt_nomemaecad.getText().equals("") && txt_nomepaicad.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o nome de algum responsável!");
        } else if (txt_nomefilhocad.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o nome do Filho(a)");
        }else if (txt_telcad.getText().equals("")&&txt_celcad.equals("")&&txt_emailcad.equals("")) {
            JOptionPane.showMessageDialog(null, "Insira algum meio de contato!");
        }else if (txt_datacad.getDate()==null) {
            JOptionPane.showMessageDialog(null, "Insira a Data da Visita!");
        } else {
            try {
                java.util.Date F = txt_datacad.getDate();
                SimpleDateFormat format1 = new SimpleDateFormat("yyyy/MM/dd");
                String datavisita = format1.format(F);

                a.setNomeMae(txt_nomemaecad.getText());
                a.setNomePai(txt_nomepaicad.getText());
                a.setNomeFilho(txt_nomefilhocad.getText());
                a.setTelefone(txt_telcad.getText());
                a.setCelular(txt_celcad.getText());
                a.setDataVisita(datavisita);
                a.setEmail(txt_emailcad.getText());
                
                
            } catch (Exception e) {

            }
            VisitaDAO adao = new VisitaDAO();
            adao.adciona(a);
            JOptionPane.showMessageDialog(null, "Visita Cadastrada com sucesso");
        }
    }//GEN-LAST:event_btn_cadActionPerformed

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed

    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_pesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesActionPerformed
        VisitaDAO ldao = new VisitaDAO();
        Visita l = new Visita();
        String campo=null;
        if(cb_pes.getSelectedIndex()==0){
            campo="Nome_Mae";
        }else if(cb_pes.getSelectedIndex()==1){
            campo="Nome_Pai";
        }else if(cb_pes.getSelectedIndex()==2){
            campo="Nome_Aluno";
        }else if(cb_pes.getSelectedIndex()==3){
            campo="Data_Visita";
        }
        

        ldao.Consultar(campo, txt_pes.getText(), l);
             
                lbl_id.setText(l.getIdVisita()+"");
               txt_nomemaecons.setText(l.getNomeMae()+"");
                txt_nomepaicons.setText(l.getNomePai()+"");
                txt_nomefilhocons.setText(l.getNomeFilho()+"");
                txt_telcons.setText(l.getTelefone()+"");
                txt_celcons.setText(l.getCelular());
                txt_datacans.setDate(l.getDate());
                txt_emailcons.setText(l.getEmail());
        
        
        

        List<Visita> visitas = ldao.getLista(campo, txt_pes.getText());
        DefaultTableModel model = (DefaultTableModel) tbl_visita.getModel();
        model.setNumRows(0);

        for (Visita visita : visitas) {
            model.addRow(new Object[]{
                visita.getIdVisita(),
                visita.getNomeMae(),
                visita.getNomePai(),
                visita.getNomeFilho(),
                visita.getTelefone(),
                visita.getCelular(),
                visita.getEmail(),
                visita.getDate()});
        }
    }//GEN-LAST:event_btn_pesActionPerformed

    private void tbl_visitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_visitaMouseClicked
         if (evt.getClickCount() == 1) {
            Integer y=0;
            VisitaDAO ldao = new VisitaDAO();
            lbl_id.setText(tbl_visita.getValueAt(tbl_visita.getSelectedRow(), 0).toString());
               txt_nomemaecons.setText(tbl_visita.getValueAt(tbl_visita.getSelectedRow(), 1).toString());
                txt_nomepaicons.setText(tbl_visita.getValueAt(tbl_visita.getSelectedRow(), 2).toString());
                txt_nomefilhocons.setText(tbl_visita.getValueAt(tbl_visita.getSelectedRow(), 3).toString());
                txt_telcons.setText(tbl_visita.getValueAt(tbl_visita.getSelectedRow(), 4).toString());
                txt_celcons.setText(tbl_visita.getValueAt(tbl_visita.getSelectedRow(), 5).toString());
                txt_datacans.setDate((Date)tbl_visita.getValueAt(tbl_visita.getSelectedRow(), 7));
                txt_emailcons.setText(tbl_visita.getValueAt(tbl_visita.getSelectedRow(), 6).toString());
        }
    }//GEN-LAST:event_tbl_visitaMouseClicked

    private void txt_pesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesKeyPressed
        btn_pesActionPerformed(null);
    }//GEN-LAST:event_txt_pesKeyPressed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        Visita a = new Visita();

        if (txt_nomemaecons.getText().equals("") && txt_nomepaicons.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o nome de algum responsável!");
        } else if (txt_nomefilhocons.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o nome do Filho(a)");
        }else if (txt_telcons.getText().equals("")&&txt_celcad.equals("")&&txt_emailcad.equals("")) {
            JOptionPane.showMessageDialog(null, "Insira algum meio de contato!");
        }else if (txt_datacans.getDate()==null) {
            JOptionPane.showMessageDialog(null, "Insira a Data da Visita!");
        } else {
            try {
                java.util.Date F = txt_datacans.getDate();
                SimpleDateFormat format1 = new SimpleDateFormat("yyyy/MM/dd");
                String datavisita = format1.format(F);

                a.setNomeMae(txt_nomemaecons.getText());
                a.setNomePai(txt_nomepaicons.getText());
                a.setNomeFilho(txt_nomefilhocons.getText());
                a.setTelefone(txt_telcons.getText());
                a.setCelular(txt_celcons.getText());
                a.setDataVisita(datavisita);
                a.setEmail(txt_emailcons.getText());
                
                
            } catch (Exception e) {

            }
            VisitaDAO adao = new VisitaDAO();
            adao.Alterar(a);
            JOptionPane.showMessageDialog(null, "Visita Alterada com sucesso");
            btn_pesActionPerformed(evt);
        }
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        Visita p = new Visita();
        int r = JOptionPane.showConfirmDialog(null, "Deseja excluir esse registro");
        if (r == 0) {
            p.setIdVisita(Integer.parseInt(lbl_id.getText()));
            VisitaDAO cdao = new VisitaDAO();
            cdao.remove(p);
            JOptionPane.showMessageDialog(null, "Visita Removida com Sucesso");
            btn_pesActionPerformed(evt);
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_novo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo4ActionPerformed
        VisitaDAO v = new VisitaDAO();
        v.gerarRelCompleto();
    }//GEN-LAST:event_btn_novo4ActionPerformed

    private void btn_novo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo5ActionPerformed
        VisitaDAO v = new VisitaDAO();
        v.gerarRelData(txt_de1, txt_ate1);
    }//GEN-LAST:event_btn_novo5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_cad;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_novo4;
    private javax.swing.JButton btn_novo5;
    private javax.swing.JButton btn_pes;
    private javax.swing.JComboBox cb_pes;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JTable tbl_visita;
    private com.toedter.calendar.JDateChooser txt_ate1;
    private javax.swing.JFormattedTextField txt_celcad;
    private javax.swing.JFormattedTextField txt_celcons;
    private com.toedter.calendar.JDateChooser txt_datacad;
    private com.toedter.calendar.JDateChooser txt_datacans;
    private com.toedter.calendar.JDateChooser txt_de1;
    private javax.swing.JTextField txt_emailcad;
    private javax.swing.JTextField txt_emailcons;
    private javax.swing.JTextField txt_nomefilhocad;
    private javax.swing.JTextField txt_nomefilhocons;
    private javax.swing.JTextField txt_nomemaecad;
    private javax.swing.JTextField txt_nomemaecons;
    private javax.swing.JTextField txt_nomepaicad;
    private javax.swing.JTextField txt_nomepaicons;
    private javax.swing.JTextField txt_pes;
    private javax.swing.JFormattedTextField txt_telcad;
    private javax.swing.JFormattedTextField txt_telcons;
    // End of variables declaration//GEN-END:variables
}
