/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semeando_futuro.view;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import semeando_futuro.dao.AlunoDAO;
import semeando_futuro.dao.DesligamentoDAO;
import semeando_futuro.dao.PresencaDAO;
import semeando_futuro.modelo.Aluno;
import semeando_futuro.modelo.Desligamento;
import semeando_futuro.modelo.Presenca;

/**
 *
 * @author Thiago
 */
public class IFrm_Desligamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrm_Desligamento
     */
    public IFrm_Desligamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cb_AlunoCad = new javax.swing.JComboBox();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_MotivoCad = new javax.swing.JTextArea();
        jLabel42 = new javax.swing.JLabel();
        txt_datacad = new com.toedter.calendar.JDateChooser();
        btn_novo = new javax.swing.JButton();
        btn_cad = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cb_pes = new javax.swing.JComboBox();
        txt_pes = new javax.swing.JTextField();
        btn_pes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_desligamento = new javax.swing.JTable();
        jLabel48 = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        btn_alterar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_MotivoCons = new javax.swing.JTextArea();
        jLabel44 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txt_dataCos = new com.toedter.calendar.JDateChooser();
        txt_RAAluno = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        btn_novo4 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_de1 = new com.toedter.calendar.JDateChooser();
        txt_ate1 = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        btn_novo5 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Desligamentos");

        jLabel10.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(1, 108, 78));
        jLabel10.setText("RA do Aluno:");

        cb_AlunoCad.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cb_AlunoCadAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cb_AlunoCad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_AlunoCadMouseClicked(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(1, 108, 78));
        jLabel43.setText("Motivo:");

        txt_MotivoCad.setColumns(20);
        txt_MotivoCad.setRows(5);
        jScrollPane3.setViewportView(txt_MotivoCad);

        jLabel42.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(1, 108, 78));
        jLabel42.setText("Data Desligamento: :");

        btn_novo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_novo.setForeground(new java.awt.Color(0, 102, 102));
        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_cad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_cad.setForeground(new java.awt.Color(0, 102, 102));
        btn_cad.setText("Cadastrar");
        btn_cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel43)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(71, 71, 71)
                            .addComponent(btn_cad, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel42)
                        .addComponent(txt_datacad, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(200, 200, 200))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(197, 197, 197)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(cb_AlunoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(335, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_datacad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(jLabel10)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cb_AlunoCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(340, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        cb_pes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RA", "Data" }));

        txt_pes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pesKeyPressed(evt);
            }
        });

        btn_pes.setText("Pesquisar");
        btn_pes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesActionPerformed(evt);
            }
        });

        tbl_desligamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "idDesligamento", "RA Aluno", "Data do Desligamento", "Motivo"
            }
        ));
        tbl_desligamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_desligamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_desligamento);

        jLabel48.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(1, 108, 78));
        jLabel48.setText("id:");

        lbl_id.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(1, 108, 78));
        lbl_id.setText("----");

        btn_alterar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_alterar.setForeground(new java.awt.Color(0, 102, 102));
        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_excluir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_excluir.setForeground(new java.awt.Color(0, 102, 102));
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        txt_MotivoCons.setColumns(20);
        txt_MotivoCons.setRows(5);
        jScrollPane4.setViewportView(txt_MotivoCons);

        jLabel44.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(1, 108, 78));
        jLabel44.setText("Motivo:");

        jLabel11.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(1, 108, 78));
        jLabel11.setText("RA do Aluno:");

        jLabel45.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(1, 108, 78));
        jLabel45.setText("Data Desligamento: :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(69, 69, 69)
                            .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel48)
                                    .addGap(39, 39, 39)))
                            .addGap(7, 7, 7)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(txt_RAAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jLabel45))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_dataCos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel44)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(75, 75, 75)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cb_pes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txt_pes, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btn_pes)))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(73, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(71, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_pes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pes))
                .addGap(158, 158, 158)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_dataCos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_id)
                        .addComponent(txt_RAAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(40, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(294, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Consulta", jPanel2);

        jLabel22.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(1, 108, 78));
        jLabel22.setText("Relatório Completo:");

        btn_novo4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_novo4.setForeground(new java.awt.Color(0, 102, 102));
        btn_novo4.setText("Gerar");
        btn_novo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo4ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(1, 108, 78));
        jLabel25.setText("Relatório por data:");

        jLabel24.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(1, 108, 78));
        jLabel24.setText("De:");

        jLabel21.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(1, 108, 78));
        jLabel21.setText("Até:");

        btn_novo5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_novo5.setForeground(new java.awt.Color(0, 102, 102));
        btn_novo5.setText("Gerar");
        btn_novo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(16, 16, 16)
                        .addComponent(btn_novo4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(txt_de1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(txt_ate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(btn_novo5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(btn_novo4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(5, 5, 5)
                        .addComponent(txt_de1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(5, 5, 5)
                        .addComponent(txt_ate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btn_novo5)))
                .addContainerGap(341, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Relatórios", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed

    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadActionPerformed
            Desligamento a = new Desligamento();

        if (txt_datacad.getDate()==null) {
            JOptionPane.showMessageDialog(null, "Selecione a Data Corretamente");
        } else if (txt_MotivoCad.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o Motivo Corretamente");
        } else {
            try {
                java.util.Date F = txt_datacad.getDate();
                SimpleDateFormat format1 = new SimpleDateFormat("yyyy/MM/dd");
                String datachamada = format1.format(F);

                a.setRAALuno(cb_AlunoCad.getSelectedItem().toString());
                a.setData_Desligamento(datachamada);
                a.setMotivo(txt_MotivoCad.getText().toString());
                
                
            } catch (Exception e) {

            }
            DesligamentoDAO adao = new DesligamentoDAO();
            adao.adciona(a);
            JOptionPane.showMessageDialog(null, "Desligamento Cadastrado com sucesso");
        }
    }//GEN-LAST:event_btn_cadActionPerformed

    private void cb_AlunoCadAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cb_AlunoCadAncestorAdded
         cb_AlunoCad.removeAllItems();
        AlunoDAO tdao = new AlunoDAO();
        List<Aluno> alunos = tdao.getList();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_AlunoCad.getModel();
        for (Aluno aluno : alunos ){
            model.addElement(aluno.getRA());
        }
    }//GEN-LAST:event_cb_AlunoCadAncestorAdded

    private void cb_AlunoCadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_AlunoCadMouseClicked
        cb_AlunoCad.removeAllItems();
        AlunoDAO tdao = new AlunoDAO();
        List<Aluno> alunos = tdao.getList();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_AlunoCad.getModel();
        for (Aluno aluno : alunos ){
            model.addElement(aluno.getRA());
        }
    }//GEN-LAST:event_cb_AlunoCadMouseClicked

    private void btn_pesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesActionPerformed
        DesligamentoDAO ldao = new DesligamentoDAO();
        Desligamento l = new Desligamento();
        String campo=null;
        if(cb_pes.getSelectedIndex()==0){
            campo="Aluno.RA";
        }else if(cb_pes.getSelectedIndex()==1){
            campo="data_Desl";
        }
        

        ldao.Consultar(campo, txt_pes.getText(), l);
             
    
  
        
        
        txt_RAAluno.setText("" + l.getRAALuno());
        lbl_id.setText(l.getIdDesligamento().toString());
        txt_dataCos.setDate(l.getDate());
        txt_MotivoCons.setText(l.getMotivo().toString());

        List<Desligamento> desligamentos = ldao.getLista(campo, txt_pes.getText());
        DefaultTableModel model = (DefaultTableModel) tbl_desligamento.getModel();
        model.setNumRows(0);

        for (Desligamento desligamento : desligamentos) {
            model.addRow(new Object[]{
                desligamento.getIdDesligamento(),
                desligamento.getRAALuno(),
                desligamento.getDate(),
                desligamento.getMotivo()});
        }
    }//GEN-LAST:event_btn_pesActionPerformed

    private void txt_pesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesKeyPressed
        btn_pesActionPerformed(null);
    }//GEN-LAST:event_txt_pesKeyPressed

    private void tbl_desligamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_desligamentoMouseClicked
         if (evt.getClickCount() == 1) {
            Integer y=0;
            DesligamentoDAO ldao = new DesligamentoDAO();
            txt_RAAluno.setText(tbl_desligamento.getValueAt(tbl_desligamento.getSelectedRow(), 1).toString());
        lbl_id.setText(tbl_desligamento.getValueAt(tbl_desligamento.getSelectedRow(), 0).toString());
        txt_dataCos.setDate((Date) tbl_desligamento.getValueAt(tbl_desligamento.getSelectedRow(), 2));
        txt_MotivoCons.setText(tbl_desligamento.getValueAt(tbl_desligamento.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_tbl_desligamentoMouseClicked

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        Desligamento a = new Desligamento();

        if (txt_dataCos.getDate()==null) {
            JOptionPane.showMessageDialog(null, "Selecione a Data Corretamente");
        } else if (txt_MotivoCons.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o Motivo Corretamente");
        } else {
            try {
                java.util.Date F = txt_dataCos.getDate();
                SimpleDateFormat format1 = new SimpleDateFormat("yyyy/MM/dd");
                String datachamada = format1.format(F);

                a.setRAALuno(txt_RAAluno.getText().toString());
                a.setData_Desligamento(datachamada);
                a.setMotivo(txt_MotivoCons.getText().toString());
                a.setIdDesligamento(Integer.parseInt(lbl_id.getText()));
                
                
            } catch (Exception e) {

            }
            DesligamentoDAO adao = new DesligamentoDAO();
            adao.Alterar(a);
            JOptionPane.showMessageDialog(null, "Desligamento Cadastrado com sucesso");
        }
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        Desligamento p = new Desligamento();
        int r = JOptionPane.showConfirmDialog(null, "Deseja excluir esse registro");
        if (r == 0) {
            p.setIdDesligamento(Integer.parseInt(lbl_id.getText()));
            DesligamentoDAO cdao = new DesligamentoDAO();
            cdao.remove(p);
            JOptionPane.showMessageDialog(null, "Desligamento Removido com Sucesso");
            btn_pesActionPerformed(evt);
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_novo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo4ActionPerformed
        DesligamentoDAO d = new DesligamentoDAO();
        d.gerarRelCompleto();
    }//GEN-LAST:event_btn_novo4ActionPerformed

    private void btn_novo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo5ActionPerformed
        DesligamentoDAO d = new DesligamentoDAO();
        d.gerarRelData(txt_de1, txt_ate1);
    }//GEN-LAST:event_btn_novo5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_cad;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_novo4;
    private javax.swing.JButton btn_novo5;
    private javax.swing.JButton btn_pes;
    private javax.swing.JComboBox cb_AlunoCad;
    private javax.swing.JComboBox cb_pes;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JTable tbl_desligamento;
    private javax.swing.JTextArea txt_MotivoCad;
    private javax.swing.JTextArea txt_MotivoCons;
    private javax.swing.JTextField txt_RAAluno;
    private com.toedter.calendar.JDateChooser txt_ate1;
    private com.toedter.calendar.JDateChooser txt_dataCos;
    private com.toedter.calendar.JDateChooser txt_datacad;
    private com.toedter.calendar.JDateChooser txt_de1;
    private javax.swing.JTextField txt_pes;
    // End of variables declaration//GEN-END:variables
}
