/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semeando_futuro.view;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import semeando_futuro.dao.AlunoDAO;
import semeando_futuro.dao.MaeDAO;
import semeando_futuro.dao.PaiDAO;
import semeando_futuro.dao.TurmaDAO;
import semeando_futuro.modelo.Aluno;
import semeando_futuro.modelo.Mae;
import semeando_futuro.modelo.Pai;
import semeando_futuro.modelo.Turma;

/**
 *
 * @author lab
 */
public class IFrm_CadAluno extends javax.swing.JInternalFrame {

    public void CursorCaneta() {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image img = toolkit.getImage("caneta.png");
        Point point = new Point(0, 0);
        Cursor cursor = toolkit.createCustomCursor(img, point, "Cursor");
        this.setCursor(cursor);
    }

    public void CursorLapis() {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image img = toolkit.getImage("lapis.png");
        Point point = new Point(0, 0);
        Cursor cursor = toolkit.createCustomCursor(img, point, "Cursor");

        btn_novo.setCursor(cursor);
        btn_cad.setCursor(cursor);
        btn_proc.setCursor(cursor);
        btn_res.setCursor(cursor);
        btn_nasc.setCursor(cursor);
        btn_vasc.setCursor(cursor);
        btn_matri.setCursor(cursor);
    }

    public IFrm_CadAluno() {
        initComponents();
        CursorCaneta();
        CursorLapis();
        lbl_CaminhoFoto.setVisible(false);
        lbl_caminhoNasc.setVisible(false);
        lbl_caminhoVasc.setVisible(false);
        lbl_caminhoRes.setVisible(false);
        lbl_caminhomatri.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_sobrenome = new javax.swing.JTextField();
        cb_turma = new javax.swing.JComboBox();
        lbl_Pai = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txt_RA = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        lbl_caminhoRes = new javax.swing.JLabel();
        lbl_AnVASC = new javax.swing.JLabel();
        lbl_AnNASC = new javax.swing.JLabel();
        btn_proc = new javax.swing.JButton();
        lblfoto = new javax.swing.JLabel();
        lbl_AnRES = new javax.swing.JLabel();
        btn_res = new javax.swing.JButton();
        lbl_caminhoNasc = new javax.swing.JLabel();
        btn_nasc = new javax.swing.JButton();
        lbl_caminhoVasc = new javax.swing.JLabel();
        btn_vasc = new javax.swing.JButton();
        lbl_AnMATRI = new javax.swing.JLabel();
        lbl_caminhomatri = new javax.swing.JLabel();
        btn_matri = new javax.swing.JButton();
        cb_RGPai = new javax.swing.JComboBox();
        cb_RGMae = new javax.swing.JComboBox();
        txt_Mensalidade = new javax.swing.JFormattedTextField();
        lbl_CaminhoFoto = new javax.swing.JLabel();
        btn_novo = new javax.swing.JButton();
        btn_cad = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Aluno");
        setPreferredSize(new java.awt.Dimension(670, 563));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(1, 108, 78));
        jLabel39.setText("Nascimento:");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel37.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(1, 108, 78));
        jLabel37.setText("Nome:");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        jLabel38.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(1, 108, 78));
        jLabel38.setText("Sobrenome:");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 70, -1));

        jLabel40.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(1, 108, 78));
        jLabel40.setText("Turma:");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jLabel43.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(1, 108, 78));
        jLabel43.setText("R.A.:");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));
        jPanel1.add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 350, -1));
        jPanel1.add(txt_sobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 350, -1));

        cb_turma.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cb_turmaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(cb_turma, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 84, -1));

        lbl_Pai.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lbl_Pai.setForeground(new java.awt.Color(1, 108, 78));
        lbl_Pai.setText("RG Pai:");
        jPanel1.add(lbl_Pai, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        jLabel42.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(1, 108, 78));
        jLabel42.setText("RG Mãe:");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel44.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(1, 108, 78));
        jLabel44.setText("Mensalidade:");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));
        jPanel1.add(txt_RA, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 110, -1));

        jLabel45.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(1, 108, 78));
        jLabel45.setText("Foto:");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        lbl_caminhoRes.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lbl_caminhoRes.setForeground(new java.awt.Color(1, 108, 78));
        jPanel1.add(lbl_caminhoRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 90, 20));

        lbl_AnVASC.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lbl_AnVASC.setForeground(new java.awt.Color(1, 108, 78));
        lbl_AnVASC.setText("An. Vacina:");
        jPanel1.add(lbl_AnVASC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        lbl_AnNASC.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lbl_AnNASC.setForeground(new java.awt.Color(1, 108, 78));
        lbl_AnNASC.setText("An. Nascimento:");
        jPanel1.add(lbl_AnNASC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        btn_proc.setForeground(new java.awt.Color(0, 102, 102));
        btn_proc.setText("Procurar");
        btn_proc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procActionPerformed(evt);
            }
        });
        jPanel1.add(btn_proc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        lblfoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(lblfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 100, 110));

        lbl_AnRES.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lbl_AnRES.setForeground(new java.awt.Color(1, 108, 78));
        lbl_AnRES.setText("An. Residência:");
        jPanel1.add(lbl_AnRES, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        btn_res.setForeground(new java.awt.Color(0, 102, 102));
        btn_res.setText("Procurar");
        btn_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resActionPerformed(evt);
            }
        });
        jPanel1.add(btn_res, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        lbl_caminhoNasc.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lbl_caminhoNasc.setForeground(new java.awt.Color(1, 108, 78));
        jPanel1.add(lbl_caminhoNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 90, 20));

        btn_nasc.setForeground(new java.awt.Color(0, 102, 102));
        btn_nasc.setText("Procurar");
        btn_nasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nascActionPerformed(evt);
            }
        });
        jPanel1.add(btn_nasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        lbl_caminhoVasc.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lbl_caminhoVasc.setForeground(new java.awt.Color(1, 108, 78));
        jPanel1.add(lbl_caminhoVasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 80, 20));

        btn_vasc.setForeground(new java.awt.Color(0, 102, 102));
        btn_vasc.setText("Procurar");
        btn_vasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vascActionPerformed(evt);
            }
        });
        jPanel1.add(btn_vasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        lbl_AnMATRI.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lbl_AnMATRI.setForeground(new java.awt.Color(1, 108, 78));
        lbl_AnMATRI.setText("An. Matrícula:");
        jPanel1.add(lbl_AnMATRI, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        lbl_caminhomatri.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lbl_caminhomatri.setForeground(new java.awt.Color(1, 108, 78));
        jPanel1.add(lbl_caminhomatri, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 100, 20));

        btn_matri.setForeground(new java.awt.Color(0, 102, 102));
        btn_matri.setText("Procurar");
        btn_matri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_matriActionPerformed(evt);
            }
        });
        jPanel1.add(btn_matri, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        cb_RGPai.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cb_RGPaiAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(cb_RGPai, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 270, -1));

        cb_RGMae.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cb_RGMaeAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(cb_RGMae, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 270, -1));

        try {
            txt_Mensalidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$####,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txt_Mensalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 120, -1));
        jPanel1.add(lbl_CaminhoFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 40, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 630, 480));

        btn_novo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_novo.setForeground(new java.awt.Color(0, 102, 102));
        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_novo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 91, 39));

        btn_cad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_cad.setForeground(new java.awt.Color(0, 102, 102));
        btn_cad.setText("Cadastrar");
        btn_cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 98, 39));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_procActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procActionPerformed
        String caminho = null;
        JFileChooser chooser = new JFileChooser("c:");
        String file = "c:";

        try {
            chooser.showOpenDialog(null);
            File n = chooser.getSelectedFile().getAbsoluteFile();
            caminho = n.toString();
            lbl_CaminhoFoto.setText(caminho);
            if (caminho != file) {
                try {
                    ImageIcon icon = new ImageIcon(caminho);
                    icon.setImage(icon.getImage().getScaledInstance(lblfoto.getWidth(), lblfoto.getHeight(), 1));
                    lblfoto.setIcon(icon);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro: " + e);
                }
            } else {
                chooser.cancelSelection();

            }

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Selecione um arquivo! Erro: " + e);

        }

    }//GEN-LAST:event_btn_procActionPerformed

    private void btn_resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resActionPerformed
        String caminho = null;
        JFileChooser chooser = new JFileChooser("c:");
        String file = "c:";

        try {
            chooser.showOpenDialog(null);
            File n = chooser.getSelectedFile().getAbsoluteFile();
            caminho = n.toString();
            if (caminho != file) {
                try {
                    lbl_caminhoRes.setText(caminho + "");
                    lbl_AnRES.setText(lbl_AnRES.getText() + " Anexado!");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro: " + e);
                }
            } else {
                chooser.cancelSelection();

            }

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Selecione um arquivo!");

        }
    }//GEN-LAST:event_btn_resActionPerformed

    private void btn_nascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nascActionPerformed
        String caminho = null;
        JFileChooser chooser = new JFileChooser("c:");
        String file = "c:";

        try {
            chooser.showOpenDialog(null);
            File n = chooser.getSelectedFile().getAbsoluteFile();
            caminho = n.toString();
            if (caminho != file) {
                try {
                    lbl_caminhoNasc.setText(caminho + "");
                    lbl_AnNASC.setText(lbl_AnNASC.getText() + " Anexado!");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro: " + e);
                }
            } else {
                chooser.cancelSelection();

            }

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Selecione um arquivo! Erro: " + e);

        }
    }//GEN-LAST:event_btn_nascActionPerformed

    private void btn_vascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vascActionPerformed
        String caminho = null;
        JFileChooser chooser = new JFileChooser("c:");
        String file = "c:";

        try {
            chooser.showOpenDialog(null);
            File n = chooser.getSelectedFile().getAbsoluteFile();
            caminho = n.toString();
            if (caminho != file) {
                try {
                    lbl_caminhoVasc.setText(caminho + "");
                    lbl_AnVASC.setText(lbl_AnVASC.getText() + " Anexado!");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro: " + e);
                }
            } else {
                chooser.cancelSelection();

            }

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Selecione um arquivo! Erro: " + e);

        }
    }//GEN-LAST:event_btn_vascActionPerformed

    private void btn_matriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_matriActionPerformed
        String caminho = null;
        JFileChooser chooser = new JFileChooser("c:");
        String file = "c:";

        try {
            chooser.showOpenDialog(null);
            File n = chooser.getSelectedFile().getAbsoluteFile();
            caminho = n.toString();
            if (caminho != file) {
                try {
                    lbl_caminhomatri.setText(caminho + "");
                    lbl_AnMATRI.setText(lbl_AnMATRI.getText() + " Anexado!");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro: " + e);
                }
            } else {
                chooser.cancelSelection();

            }

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Selecione um arquivo! Erro: " + e);

        }
    }//GEN-LAST:event_btn_matriActionPerformed

    private void btn_cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadActionPerformed
        Aluno a = new Aluno();

        if (txt_nome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o nome corretamente");
        } else if (txt_sobrenome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o sobrenome corretamente");
        }else if (txt_nasc.getDate()==null) {
            JOptionPane.showMessageDialog(null, "Digite a data de nascimento corretamente");
        }else if (txt_RA.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o RA do aluno corretamente");
        }else if(txt_Mensalidade.getText().equals("R$    ,  ")){
            JOptionPane.showMessageDialog(null, "Digite a Mensalidade do aluno corretamente");
        }else if (lbl_AnMATRI.getText().equals("An. Matrícula:")) {
            JOptionPane.showMessageDialog(null, "Anexe a Matrícula corretamente");
        }else if (lbl_AnNASC.getText().equals("An. Nascimento:")) {
            JOptionPane.showMessageDialog(null, "Anexe a Certidão corretamente");
        }else if (lbl_AnRES.getText().equals("An. Residência:")) {
            JOptionPane.showMessageDialog(null, "Anexe o Comprovante de Residência corretamente");
        }else if (lbl_AnVASC.getText().equals("An. Vacina:")) {
            JOptionPane.showMessageDialog(null, "Anexe a Carteira de Vacinação corretamente");
        } else {
            try {
                java.util.Date F = txt_nasc.getDate();
                SimpleDateFormat format1 = new SimpleDateFormat("yyyy/MM/dd");
                String datanasc = format1.format(F);

                a.setNome(txt_nome.getText());
                a.setSobrenome(txt_sobrenome.getText());
                a.setNascimento(datanasc);
                a.setTurma(cb_turma.getSelectedItem().toString());              
                a.setRA(txt_RA.getText());
                a.setMensalidade(Double.parseDouble(txt_Mensalidade.getText().replace(",", ".").replace("R$", "")));
                a.setRG_Mae(cb_RGMae.getSelectedItem().toString());
                a.setRG_Pai(cb_RGPai.getSelectedItem().toString());
                a.setCaminhoFoto(lbl_CaminhoFoto.getText());
                a.setCaminhoCert(lbl_caminhoNasc.getText());
                a.setCaminhoMatri(lbl_caminhomatri.getText());
                a.setCaminhoVac(lbl_caminhoVasc.getText());
                a.setCaminhoRes(lbl_caminhoRes.getText());
                
            } catch (Exception e) {

            }
            AlunoDAO adao = new AlunoDAO();
            adao.adciona(a);
            JOptionPane.showMessageDialog(null, "Aluno Cadastrado com sucesso");
        }


    }//GEN-LAST:event_btn_cadActionPerformed

    private void cb_turmaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cb_turmaAncestorAdded
        TurmaDAO tdao = new TurmaDAO();
        List<Turma> turmas = tdao.getList();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_turma.getModel();
        for (Turma turma : turmas ){
            model.addElement(turma.getNome_Turma());
        }
    }//GEN-LAST:event_cb_turmaAncestorAdded

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        lbl_CaminhoFoto.setText(null);
        lbl_caminhoNasc.setText(null);
        lbl_caminhoRes.setText(null);
        lbl_caminhomatri.setText(null);
        lbl_caminhoVasc.setText(null);
        txt_Mensalidade.setText(null);
        txt_RA.setText(null);
        txt_nasc.setDate(null);
        txt_nome.setText(null);
        txt_sobrenome.setText(null);
        cb_RGMae.setSelectedIndex(0);
        cb_RGPai.setSelectedIndex(0);
        cb_turma.setSelectedIndex(0);
        lblfoto.setIcon(null);
        lbl_AnMATRI.setText("An. Matrícula:");
        lbl_AnNASC.setText("An. Nascimento:");
        lbl_AnRES.setText("An. Residência:");
        lbl_AnVASC.setText("An. Vacina:");
        
        
    }//GEN-LAST:event_btn_novoActionPerformed

    private void cb_RGPaiAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cb_RGPaiAncestorAdded
        PaiDAO tdao = new PaiDAO();
        List<Pai> pais = tdao.getList();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_RGPai.getModel();
        for (Pai pai : pais ){
            model.addElement(pai.getRG());
        }
    }//GEN-LAST:event_cb_RGPaiAncestorAdded

    private void cb_RGMaeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cb_RGMaeAncestorAdded
        MaeDAO tdao = new MaeDAO();
        List<Mae> maes = tdao.getList();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_RGMae.getModel();
        for (Mae mae : maes ){
            model.addElement(mae.getRG());
        }
    }//GEN-LAST:event_cb_RGMaeAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cad;
    private javax.swing.JButton btn_matri;
    private javax.swing.JButton btn_nasc;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_proc;
    private javax.swing.JButton btn_res;
    private javax.swing.JButton btn_vasc;
    private javax.swing.JComboBox cb_RGMae;
    private javax.swing.JComboBox cb_RGPai;
    private javax.swing.JComboBox cb_turma;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_AnMATRI;
    private javax.swing.JLabel lbl_AnNASC;
    private javax.swing.JLabel lbl_AnRES;
    private javax.swing.JLabel lbl_AnVASC;
    private javax.swing.JLabel lbl_CaminhoFoto;
    private javax.swing.JLabel lbl_Pai;
    private javax.swing.JLabel lbl_caminhoNasc;
    private javax.swing.JLabel lbl_caminhoRes;
    private javax.swing.JLabel lbl_caminhoVasc;
    private javax.swing.JLabel lbl_caminhomatri;
    private javax.swing.JLabel lblfoto;
    private javax.swing.JFormattedTextField txt_Mensalidade;
    private javax.swing.JTextField txt_RA;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_sobrenome;
    // End of variables declaration//GEN-END:variables
}
