/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semeando_futuro.view;


import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import semeando_futuro.dao.AlunoDAO;
import semeando_futuro.dao.FuncionarioDAO;
import semeando_futuro.dao.LoginDAO;
import semeando_futuro.modelo.Aluno;
import semeando_futuro.modelo.Funcionario;
import semeando_futuro.modelo.Login;
import sun.java2d.loops.MaskBlit;
import sun.java2d.loops.MaskFill;

/**
 *
 * @author lab
 */
public class IFrm_CadFunc extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrm_Func
     */
    public IFrm_CadFunc() {
        initComponents();
        gerarbanco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Cep = new javax.swing.JFormattedTextField();
        txt_tel = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        cb_estado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_cidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_bairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_end = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_localNasc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cb_EstadoCivil = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cb_sexo = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txt_parceiro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_pai = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_mae = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_cartPro = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        cb_UF = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txt_emprego = new javax.swing.JTextField();
        txt_Empresa = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        cb_banco = new javax.swing.JComboBox<>();
        txt_agencia = new javax.swing.JFormattedTextField();
        txt_conta = new javax.swing.JFormattedTextField();
        txt_nasc = new com.toedter.calendar.JDateChooser();
        txt_pis = new javax.swing.JFormattedTextField();
        txt_cpf = new javax.swing.JFormattedTextField();
        txt_rg = new javax.swing.JFormattedTextField();
        txt_dataCartPro = new com.toedter.calendar.JDateChooser();
        txt_dataRG = new com.toedter.calendar.JDateChooser();
        cb_OrgaoEmissorRG = new javax.swing.JComboBox();
        txt_CR = new javax.swing.JFormattedTextField();
        cb_OrgaoEmissorCR = new javax.swing.JComboBox();
        txt_Eleitor = new javax.swing.JFormattedTextField();
        cb_escolaridade = new javax.swing.JComboBox<>();
        btn_cadFunc = new javax.swing.JButton();
        btn_novoFunc = new javax.swing.JButton();
        txt_seccao = new javax.swing.JFormattedTextField();
        txt_zona = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        txt_nome1 = new javax.swing.JTextField();
        txt_usuario = new javax.swing.JTextField();
        txt_senha = new javax.swing.JPasswordField();
        txt_confsenha = new javax.swing.JPasswordField();
        cb_pes = new javax.swing.JComboBox<>();
        txt_pes = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Login = new javax.swing.JTable();
        btn_novoUser = new javax.swing.JButton();
        btn_cadUser = new javax.swing.JButton();
        btn_ExcluirUser = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        lbl_Cod = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        btn_AlterarUser = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Funcionário");
        setMaximumSize(new java.awt.Dimension(970, 660));
        setMinimumSize(new java.awt.Dimension(970, 660));
        setPreferredSize(new java.awt.Dimension(970, 660));

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(970, 660));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(970, 660));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(970, 660));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(970, 660));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(970, 660));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(970, 660));

        jPanel2.setMaximumSize(new java.awt.Dimension(970, 660));
        jPanel2.setMinimumSize(new java.awt.Dimension(970, 660));
        jPanel2.setPreferredSize(new java.awt.Dimension(970, 800));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 108, 78));
        jLabel2.setText("Nome Completo:");

        jLabel6.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(1, 108, 78));
        jLabel6.setText("CEP :");

        try {
            txt_Cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txt_tel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(1, 108, 78));
        jLabel8.setText("Telefone :");

        cb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC ", "AL ", "AP ", "AM ", "BA ", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG ", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS ", "RO ", "RR ", "SC ", "SP ", "SE ", "TO" }));

        jLabel4.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 108, 78));
        jLabel4.setText("Estado:");

        jLabel7.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(1, 108, 78));
        jLabel7.setText("Cidade :");

        jLabel5.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 108, 78));
        jLabel5.setText("Bairro :");

        jLabel17.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(1, 108, 78));
        jLabel17.setText("Endereço:");

        jLabel12.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(1, 108, 78));
        jLabel12.setText("Local de Nascimento :");

        jLabel11.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(1, 108, 78));
        jLabel11.setText("Data Nascimento :");

        cb_EstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro(a)", "Casado(a)", "Viúvo(a)", "Divorciado(a)" }));

        jLabel9.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(1, 108, 78));
        jLabel9.setText("Estado Civil:");

        cb_sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));

        jLabel10.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(1, 108, 78));
        jLabel10.setText("Sexo:");

        jLabel13.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(1, 108, 78));
        jLabel13.setText("Nome da Esposa(o):");

        jLabel15.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(1, 108, 78));
        jLabel15.setText("Nome do Pai:");

        jLabel16.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(1, 108, 78));
        jLabel16.setText("Nome da Mãe:");

        jLabel18.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel18.setText("DADOS PESSOAIS");

        jLabel19.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(1, 108, 78));
        jLabel19.setText("Data de Emissão :");

        jLabel20.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(1, 108, 78));
        jLabel20.setText("UF :");

        jLabel21.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(1, 108, 78));
        jLabel21.setText("Título de Eleitor Nº:");

        jLabel22.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(1, 108, 78));
        jLabel22.setText("Data de Emissão :");

        jLabel23.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(1, 108, 78));
        jLabel23.setText("Orgão Emissor :");

        jLabel24.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(1, 108, 78));
        jLabel24.setText("RG :");

        jLabel25.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(1, 108, 78));
        jLabel25.setText("Certificado Reservista :");

        jLabel27.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(1, 108, 78));
        jLabel27.setText("Orgão Emissor :");

        jLabel29.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(1, 108, 78));
        jLabel29.setText("Zona :");

        jLabel30.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(1, 108, 78));
        jLabel30.setText("PIS Nº :");

        jLabel31.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(1, 108, 78));
        jLabel31.setText("Secção :");

        jLabel32.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(1, 108, 78));
        jLabel32.setText("CPF :");

        cb_UF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC ", "AL ", "AP ", "AM ", "BA ", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG ", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS ", "RO ", "RR ", "SC ", "SP ", "SE ", "TO" }));

        jLabel33.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(1, 108, 78));
        jLabel33.setText("Escolaridade:");

        jLabel34.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(1, 108, 78));
        jLabel34.setText("Primeiro Emprego:");

        jLabel38.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(1, 108, 78));
        jLabel38.setText("Empresa:");

        jLabel35.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(1, 108, 78));
        jLabel35.setText("Carteira Profissional :");

        jLabel36.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel36.setText("CONTA BANCÁRIA PARA DEPÓSITO");

        jLabel37.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel37.setText("DOCUMENTOS");

        jLabel39.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(1, 108, 78));
        jLabel39.setText("Nº da Conta Corrente :");

        jLabel40.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(1, 108, 78));
        jLabel40.setText("Agencia :");

        jLabel41.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(1, 108, 78));
        jLabel41.setText("Banco :");

        cb_banco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Itaú", "Bradesco", "Santander", "Caixa", "Banco do Brasil", "HSBC", "Safra" }));
        cb_banco.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_bancoItemStateChanged(evt);
            }
        });

        try {
            txt_pis.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.#####.##-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txt_rg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cb_OrgaoEmissorRG.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SSP/AC", "SSP/AL", "SSP/AP", "SSP/AM", "SSP/BA", "SSP/CE", "SSP/DF", "SSP/ES", "SSP/GO", "SSP/MA", "SSP/MT", "SSP/MS", "SSP/MG", "SSP/PA", "SSP/PB", "SSP/PR", "SSP/PE", "SSP/PI", "SSP/RJ", "SSP/RN", "SSP/RS", "SSP/RO", "SSP/RR", "SSP/SC", "SSP/SP", "SSP/SE", "SSP/TO" }));

        try {
            txt_CR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cb_OrgaoEmissorCR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ministério da Defesa" }));

        try {
            txt_Eleitor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cb_escolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ensino Médio Incompleto", "Cursando Ensino Médio", "Ensino Médio Completo", "Cursando Ensino Técnico", "Ensino Técnico Completo", "Cursando Ensino Superior", "Ensino Superior Completo" }));

        btn_cadFunc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_cadFunc.setForeground(new java.awt.Color(0, 102, 102));
        btn_cadFunc.setText("Cadastrar");
        btn_cadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadFuncActionPerformed(evt);
            }
        });

        btn_novoFunc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_novoFunc.setForeground(new java.awt.Color(0, 102, 102));
        btn_novoFunc.setText("Novo");
        btn_novoFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoFuncActionPerformed(evt);
            }
        });

        try {
            txt_seccao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txt_zona.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(jLabel18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addGap(224, 224, 224)
                        .addComponent(jLabel4)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel7)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel5)
                        .addGap(98, 98, 98)
                        .addComponent(jLabel17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txt_end, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6)
                        .addGap(98, 98, 98)
                        .addComponent(jLabel8)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel10)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel9)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel11)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txt_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cb_EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txt_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txt_localNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel13)
                        .addGap(224, 224, 224)
                        .addComponent(jLabel15)
                        .addGap(204, 204, 204)
                        .addComponent(jLabel16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txt_parceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txt_pai, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txt_mae, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(jLabel37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel35)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel19)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel20)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel32)
                        .addGap(169, 169, 169)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txt_cartPro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txt_dataCartPro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(cb_UF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(txt_pis, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel24)
                        .addGap(135, 135, 135)
                        .addComponent(jLabel22)
                        .addGap(106, 106, 106)
                        .addComponent(jLabel27)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txt_dataRG, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(cb_OrgaoEmissorRG, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txt_CR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(cb_OrgaoEmissorCR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel34)
                        .addGap(212, 212, 212)
                        .addComponent(jLabel38)
                        .addGap(244, 244, 244)
                        .addComponent(jLabel33))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txt_emprego, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txt_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cb_escolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel36))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel41)
                        .addGap(267, 267, 267)
                        .addComponent(jLabel40)
                        .addGap(186, 186, 186)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(cb_banco, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txt_agencia, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txt_conta, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(txt_Eleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(txt_zona, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_seccao, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(btn_novoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btn_cadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel18)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_localNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_parceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel37)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel32)
                    .addComponent(jLabel30))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_cartPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dataCartPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_UF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel22)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dataRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_OrgaoEmissorRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_CR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_OrgaoEmissorCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel29)
                    .addComponent(jLabel31))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Eleitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_zona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_seccao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jLabel38)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_emprego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_escolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel36)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addComponent(jLabel40)
                    .addComponent(jLabel39))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_banco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_agencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_conta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_novoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel2);

        jTabbedPane1.addTab("Cadastro de Funcionário", jScrollPane1);

        jPanel1.setMaximumSize(new java.awt.Dimension(970, 660));
        jPanel1.setMinimumSize(new java.awt.Dimension(970, 660));
        jPanel1.setPreferredSize(new java.awt.Dimension(970, 660));

        cb_pes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_pes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nome", "Usuário" }));

        txt_pes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pesKeyPressed(evt);
            }
        });

        tbl_Login.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbl_Login.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Usuario"
            }
        ));
        jScrollPane2.setViewportView(tbl_Login);

        btn_novoUser.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_novoUser.setForeground(new java.awt.Color(0, 102, 102));
        btn_novoUser.setText("Novo");
        btn_novoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoUserActionPerformed(evt);
            }
        });

        btn_cadUser.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_cadUser.setForeground(new java.awt.Color(0, 102, 102));
        btn_cadUser.setText("Cadastrar");
        btn_cadUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadUserActionPerformed(evt);
            }
        });

        btn_ExcluirUser.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_ExcluirUser.setForeground(new java.awt.Color(0, 102, 102));
        btn_ExcluirUser.setText("Excluir");
        btn_ExcluirUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirUserActionPerformed(evt);
            }
        });

        btn_consultar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_consultar.setForeground(new java.awt.Color(0, 102, 102));
        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(1, 108, 78));
        jLabel52.setText("id:");

        lbl_Cod.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lbl_Cod.setForeground(new java.awt.Color(1, 108, 78));
        lbl_Cod.setText("----");

        jLabel43.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(1, 108, 78));
        jLabel43.setText("Confirmar senha:");

        jLabel44.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(1, 108, 78));
        jLabel44.setText("Nome:");

        jLabel45.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(1, 108, 78));
        jLabel45.setText("Usuario:");

        jLabel46.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(1, 108, 78));
        jLabel46.setText("Senha:");

        btn_AlterarUser.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_AlterarUser.setForeground(new java.awt.Color(0, 102, 102));
        btn_AlterarUser.setText("Alterar");
        btn_AlterarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AlterarUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel52)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lbl_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(txt_nome1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(txt_confsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btn_novoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(btn_cadUser, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(btn_ExcluirUser, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(btn_AlterarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cb_pes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt_pes, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52)
                    .addComponent(jLabel44))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Cod)
                    .addComponent(txt_nome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45)
                    .addComponent(jLabel46))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel43)
                .addGap(5, 5, 5)
                .addComponent(txt_confsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_novoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadUser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ExcluirUser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_AlterarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_pes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_pes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro de Login", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ExcluirUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirUserActionPerformed
        semeando_futuro.modelo.Login l = new Login();
        int r = JOptionPane.showConfirmDialog(null, "Deseja excluir esse registro");
        if (r == 0) {
            l.setCod_login(Integer.parseInt(lbl_Cod.getText()));
            LoginDAO cdao = new LoginDAO();
            cdao.remove(l);
            JOptionPane.showMessageDialog(null, "Cliente Removodo com Sucesso");
            btn_consultarActionPerformed(evt);
        }
    }//GEN-LAST:event_btn_ExcluirUserActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        LoginDAO ldao = new LoginDAO();
        Login l = new Login();
        String campo = null;
        if (cb_pes.getSelectedIndex() == 0) {
            campo = "idLogin";
        } else if (cb_pes.getSelectedIndex() == 1) {
            campo = "nome";
        } else if (cb_pes.getSelectedIndex() == 2) {
            campo = "Usuario";
        }
        ldao.Consultar(campo, txt_pes.getText(), l);

        lbl_Cod.setText("" + l.getCod_login());
        txt_nome.setText("" + l.getNome());
        txt_usuario.setText("" + l.getUsuario());
        txt_senha.setText("" + l.getSenha());
        txt_confsenha.setText("" + l.getSenha());

        List<Login> logins = ldao.getLista(campo, txt_pes.getText());
        DefaultTableModel model = (DefaultTableModel) tbl_Login.getModel();
        model.setNumRows(0);

        for (Login log : logins) {
            model.addRow(new Object[]{
                log.getCod_login(),
                log.getNome(),
                log.getUsuario(),});
        }
        if (txt_nome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Usuario Não Cadastrado", "Aviso", JOptionPane.WARNING_MESSAGE);
        }    
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void cb_bancoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_bancoItemStateChanged
        gerarbanco();
    }//GEN-LAST:event_cb_bancoItemStateChanged

    private void btn_cadUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadUserActionPerformed
        String senha = txt_senha.getText();
        String confsenha = txt_confsenha.getText();
        if (senha.equals(confsenha)) {
            Login l = new Login();
            try {
                l.setNome(txt_nome1.getText());
                l.setUsuario(txt_usuario.getText());
                l.setSenha(txt_senha.getText());
            } catch (Exception e) {
            }
            LoginDAO ldao = new LoginDAO();
            ldao.adciona(l);
            JOptionPane.showMessageDialog(null, "Usuario Cadastrado com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "As senhas não conferem!");
        }
    }//GEN-LAST:event_btn_cadUserActionPerformed

    private void btn_AlterarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AlterarUserActionPerformed
        String senha = txt_senha.getText();
        String confsenha = txt_confsenha.getText();
        if (senha.equals(confsenha)) {
            Login l = new Login();
            l.setCod_login(Integer.parseInt(lbl_Cod.getText()));
            l.setNome(txt_nome.getText());
            l.setUsuario(txt_usuario.getText());
            l.setSenha(txt_senha.getText());

            LoginDAO ldao = new LoginDAO();
            ldao.Alterar(l);
            JOptionPane.showMessageDialog(null, "Cadastro de cliente Alterado com sucesso");
            btn_consultarActionPerformed(evt);
        } else {
            JOptionPane.showMessageDialog(null, "As senhas não conferem!");
        }
    }//GEN-LAST:event_btn_AlterarUserActionPerformed

    private void btn_cadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadFuncActionPerformed
        Funcionario a = new Funcionario();

        if (txt_nome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o nome corretamente");
        } else if (txt_cidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite oa cidade corretamente");
        }else if (txt_bairro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o bairro corretamente");
        }else if(txt_end.getText().equals("R$    ,  ")){
            JOptionPane.showMessageDialog(null, "Digite o endereço corretamente");
        }else if (txt_Cep.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o CEP corretamente");
        }else if (txt_tel.getText().equals("(  )    -    ")) {
            JOptionPane.showMessageDialog(null, "Digite o Telefone corretamente");
        }else if (txt_nasc.getDate()==null) {
            JOptionPane.showMessageDialog(null, "Indique a Data de Nascimento corretamente");
        }else if(txt_cartPro.getText().equals("R$    ,  ")){
            JOptionPane.showMessageDialog(null, "Digite a Carteira Profissional corretamente");
        }else if (txt_dataCartPro.getDate()==null) {
            JOptionPane.showMessageDialog(null, "Indique a data de Emissão da Carteira Profissional corretamente");
        }else if (txt_cpf.getText()==null) {
            JOptionPane.showMessageDialog(null, "Digite o CPF corretamente");
        }else if (txt_pis.getText()==null) {
            JOptionPane.showMessageDialog(null, "Digite o PIS corretamente");
        }else if(txt_rg.getText()==null){
            JOptionPane.showMessageDialog(null, "Digite o RG corretamente");
        }else if(txt_dataRG.getDate()==null){
            JOptionPane.showMessageDialog(null, "Indique a Data de emissão do RG corretamente");
        }else if (txt_CR.getText()==null) {
            JOptionPane.showMessageDialog(null, "Digite o Certificado Reservista corretamente");
        }else if (txt_Eleitor.getText()==null) {
            JOptionPane.showMessageDialog(null, "Digite o Numero de Eleitor corretamente");
        }else if (txt_zona.getText()==null) {
            JOptionPane.showMessageDialog(null, "Digite a Zona de Eleitor corretamente");
        }else if(txt_seccao.getText()==null){
            JOptionPane.showMessageDialog(null, "Digite a Secção Eleitoral corretamente");
        }else {
            try {
                java.util.Date DataNasc = txt_nasc.getDate();
                java.util.Date DataEmissaoCart = txt_dataCartPro.getDate();
                java.util.Date DataEmissaoIdent = txt_dataRG.getDate();
                SimpleDateFormat format1 = new SimpleDateFormat("yyyy/MM/dd");
                String datanasc = format1.format(DataNasc);
                String dataemissaocart = format1.format(DataEmissaoCart);
                String dataemissaoident = format1.format(DataEmissaoIdent);

                a.setNome(txt_nome.getText());
                a.setEstado(cb_estado.getSelectedItem().toString());
                a.setCidade(txt_cidade.getText());
                a.setBairro(txt_bairro.getText());
                a.setEnderecoFun(txt_end.getText());
                a.setCep(txt_Cep.getText());
                a.setTelefone(txt_tel.getText());
                a.setSexo(cb_sexo.getSelectedItem().toString());
                a.setEstado_Civil(cb_EstadoCivil.getSelectedItem().toString());
                a.setDt_Nascimento(datanasc);
                a.setLocal_Nascimento(datanasc);
                a.setNome_Parceiro(txt_parceiro.getText());
                a.setNome_Mae(txt_mae.getText());
                a.setNome_Pai(txt_pai.getText());
                a.setCart_Profissional(txt_cartPro.getText());
                a.setData_Emissao_CartPro(dataemissaocart);
                a.setUF(cb_UF.getSelectedItem().toString());
                a.setEscolaridade(cb_escolaridade.getSelectedItem().toString());
                a.setEmpresa(txt_Empresa.getText());
                a.setPrimeiro_Emprego(txt_emprego.getText());
                a.setCPF(txt_cpf.getText());
                a.setPIS(txt_pis.getText());
                a.setIdentidade(txt_rg.getText());
                a.setData_Emissao_Ident(dataemissaoident);
                a.setOrgao_emissor_Ident(cb_OrgaoEmissorRG.getSelectedItem().toString());
                a.setCertificado_Reservista(txt_CR.getText());
                a.setOrgao_Emissor_CertReserv(cb_OrgaoEmissorCR.getSelectedItem().toString());
                a.setTitulo_de_Eleitor(txt_Eleitor.getText());
                a.setZona(txt_zona.getText());
                a.setSeccao(txt_seccao.getText());
                a.setBanco(cb_banco.getSelectedItem().toString());
                a.setAgencia(txt_agencia.getText());
                a.setConta_corrente(txt_conta.getText());

            } catch (Exception e) {

            }
            FuncionarioDAO adao = new FuncionarioDAO();
            adao.adciona(a);
            JOptionPane.showMessageDialog(null, "Funcionário Cadastrado com sucesso");
        }
    }//GEN-LAST:event_btn_cadFuncActionPerformed

    private void btn_novoFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_novoFuncActionPerformed

    private void btn_novoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoUserActionPerformed
        txt_nome1.setText(null);
        txt_usuario.setText(null);
        txt_senha.setText(null);
        txt_confsenha.setText(null);
    }//GEN-LAST:event_btn_novoUserActionPerformed

    private void txt_pesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesKeyPressed
        btn_consultarActionPerformed(null);
    }//GEN-LAST:event_txt_pesKeyPressed


    private void gerarbanco(){
        if (cb_banco.getSelectedIndex() == 0) {            
            try {
                txt_agencia.setFormatterFactory(null);
                txt_conta.setFormatterFactory(null);
                MaskFormatter tfagencia = new MaskFormatter("****");
                MaskFormatter tfconta = new MaskFormatter("*****-*");
                txt_agencia.setFormatterFactory(new DefaultFormatterFactory(tfagencia));
                txt_conta.setFormatterFactory(new DefaultFormatterFactory(tfconta));
                txt_agencia.setValue(null);
                txt_conta.setValue(null);
            } catch (ParseException ex) { 
                JOptionPane.showMessageDialog(null, "Erro  " + ex);
            }           
        } else if (cb_banco.getSelectedIndex()==1){
            try {
                txt_agencia.setFormatterFactory(null);
                txt_conta.setFormatterFactory(null);
                MaskFormatter tfagencia = new MaskFormatter("****");
                MaskFormatter tfconta = new MaskFormatter("*******-*");
                txt_agencia.setFormatterFactory(new DefaultFormatterFactory(tfagencia));
                txt_conta.setFormatterFactory(new DefaultFormatterFactory(tfconta));
                txt_agencia.setValue(null);
                txt_conta.setValue(null);
            } catch (ParseException ex) {   
                JOptionPane.showMessageDialog(null, "Erro  " + ex);
            } 
        }else if (cb_banco.getSelectedIndex()==2){
            try {
                txt_agencia.setFormatterFactory(null);
                txt_conta.setFormatterFactory(null);
                MaskFormatter tfagencia = new MaskFormatter("****");
                MaskFormatter tfconta = new MaskFormatter("********-*");
                txt_agencia.setFormatterFactory(new DefaultFormatterFactory(tfagencia));
                txt_conta.setFormatterFactory(new DefaultFormatterFactory(tfconta)); 
                txt_agencia.setValue(null);
                txt_conta.setValue(null);
            } catch (ParseException ex) {   
                JOptionPane.showMessageDialog(null, "Erro  " + ex);
            } 
        }else if (cb_banco.getSelectedIndex()==3){
            try {
                txt_agencia.setFormatterFactory(null);
                txt_conta.setFormatterFactory(null);
                MaskFormatter tfagencia = new MaskFormatter("****");
                MaskFormatter tfconta = new MaskFormatter("********-*");
                txt_agencia.setFormatterFactory(new DefaultFormatterFactory(tfagencia));
                txt_conta.setFormatterFactory(new DefaultFormatterFactory(tfconta));
                txt_agencia.setValue(null);
                txt_conta.setValue(null);
            } catch (ParseException ex) {   
                JOptionPane.showMessageDialog(null, "Erro  " + ex);
            } 
        }else if (cb_banco.getSelectedIndex()==4){
            try {
                txt_agencia.setFormatterFactory(null);
                txt_conta.setFormatterFactory(null);
                MaskFormatter tfagencia = new MaskFormatter("****-*");
                MaskFormatter tfconta = new MaskFormatter("*****-*");
                txt_agencia.setFormatterFactory(new DefaultFormatterFactory(tfagencia));
                txt_conta.setFormatterFactory(new DefaultFormatterFactory(tfconta));   
                txt_agencia.setValue(null);
                txt_conta.setValue(null);
            } catch (ParseException ex) {   
                JOptionPane.showMessageDialog(null, "Erro  " + ex);
            } 
        }else if (cb_banco.getSelectedIndex()==5){
            try {
                txt_agencia.setFormatterFactory(null);
                txt_conta.setFormatterFactory(null);
                MaskFormatter tfagencia = new MaskFormatter("****");
                MaskFormatter tfconta = new MaskFormatter("*****-**");
                txt_agencia.setFormatterFactory(new DefaultFormatterFactory(tfagencia));
                txt_conta.setFormatterFactory(new DefaultFormatterFactory(tfconta));  
                txt_agencia.setValue(null);
                txt_conta.setValue(null);
            } catch (ParseException ex) {   
                JOptionPane.showMessageDialog(null, "Erro  " + ex);
            } 
        }else if (cb_banco.getSelectedIndex()==6){
            try {
                txt_agencia.setFormatterFactory(null);
                txt_conta.setFormatterFactory(null);
                MaskFormatter tfagencia = new MaskFormatter("****");
                MaskFormatter tfconta = new MaskFormatter("******-*");
                txt_agencia.setFormatterFactory(new DefaultFormatterFactory(tfagencia));
                txt_conta.setFormatterFactory(new DefaultFormatterFactory(tfconta)); 
                txt_agencia.setValue(null);
                txt_conta.setValue(null);
            } catch (ParseException ex) {   
                JOptionPane.showMessageDialog(null, "Erro  " + ex);
            } 
        }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AlterarUser;
    private javax.swing.JButton btn_ExcluirUser;
    private javax.swing.JButton btn_cadFunc;
    private javax.swing.JButton btn_cadUser;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_novoFunc;
    private javax.swing.JButton btn_novoUser;
    private javax.swing.JComboBox cb_EstadoCivil;
    private javax.swing.JComboBox cb_OrgaoEmissorCR;
    private javax.swing.JComboBox cb_OrgaoEmissorRG;
    private javax.swing.JComboBox cb_UF;
    private javax.swing.JComboBox<String> cb_banco;
    private javax.swing.JComboBox<String> cb_escolaridade;
    private javax.swing.JComboBox<String> cb_estado;
    private javax.swing.JComboBox<String> cb_pes;
    private javax.swing.JComboBox cb_sexo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_Cod;
    private javax.swing.JTable tbl_Login;
    private javax.swing.JFormattedTextField txt_CR;
    private javax.swing.JFormattedTextField txt_Cep;
    private javax.swing.JFormattedTextField txt_Eleitor;
    private javax.swing.JTextField txt_Empresa;
    private javax.swing.JFormattedTextField txt_agencia;
    private javax.swing.JTextField txt_bairro;
    private javax.swing.JTextField txt_cartPro;
    private javax.swing.JTextField txt_cidade;
    private javax.swing.JPasswordField txt_confsenha;
    private javax.swing.JFormattedTextField txt_conta;
    private javax.swing.JFormattedTextField txt_cpf;
    private com.toedter.calendar.JDateChooser txt_dataCartPro;
    private com.toedter.calendar.JDateChooser txt_dataRG;
    private javax.swing.JTextField txt_emprego;
    private javax.swing.JTextField txt_end;
    private javax.swing.JTextField txt_localNasc;
    private javax.swing.JTextField txt_mae;
    private com.toedter.calendar.JDateChooser txt_nasc;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_nome1;
    private javax.swing.JTextField txt_pai;
    private javax.swing.JTextField txt_parceiro;
    private javax.swing.JTextField txt_pes;
    private javax.swing.JFormattedTextField txt_pis;
    private javax.swing.JFormattedTextField txt_rg;
    private javax.swing.JFormattedTextField txt_seccao;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JFormattedTextField txt_tel;
    private javax.swing.JTextField txt_usuario;
    private javax.swing.JFormattedTextField txt_zona;
    // End of variables declaration//GEN-END:variables
}
