/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package semeando_futuro.view;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import semeando_futuro.dao.AlunoDAO;
import semeando_futuro.dao.FuncionarioDAO;
import semeando_futuro.dao.MaeDAO;
import semeando_futuro.dao.PresencaDAO;
import semeando_futuro.dao.TurmaDAO;
import semeando_futuro.modelo.Aluno;
import semeando_futuro.modelo.Funcionario;
import semeando_futuro.modelo.Mae;
import semeando_futuro.modelo.Presenca;
import semeando_futuro.modelo.Turma;

/**
 *
 * @author lab
 */
public class IFrm_Presenca extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrm_Chamada
     */
    public IFrm_Presenca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cb_TurmaCad = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cb_FuncCad = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        cb_AlunoCad = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        txt_dataCad = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        txt_aulasCad = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_FaltasCad = new javax.swing.JTextField();
        btn_novo = new javax.swing.JButton();
        btn_cad = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_id = new javax.swing.JLabel();
        cb_FuncCons = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_dataCons = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        txt_AulaCons = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_FaltaCons = new javax.swing.JTextField();
        cb_pes = new javax.swing.JComboBox();
        txt_Pes = new javax.swing.JTextField();
        btn_Pes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_presenca = new javax.swing.JTable();
        btn_alterar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txt_RAAluno = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        btn_novo2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_ate1 = new com.toedter.calendar.JDateChooser();
        jLabel24 = new javax.swing.JLabel();
        txt_de1 = new com.toedter.calendar.JDateChooser();
        btn_novo4 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_RA1 = new javax.swing.JTextField();
        btn_novo5 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt_de2 = new com.toedter.calendar.JDateChooser();
        jLabel31 = new javax.swing.JLabel();
        txt_ate2 = new com.toedter.calendar.JDateChooser();
        btn_novo7 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txt_RA2 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Chamada");

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 108, 78));
        jLabel5.setText("Turma:");

        cb_TurmaCad.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cb_TurmaCadAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(1, 108, 78));
        jLabel11.setText("Funcionário (Resp.):");

        cb_FuncCad.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cb_FuncCadAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(1, 108, 78));
        jLabel12.setText("RA Aluno:");

        cb_AlunoCad.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cb_AlunoCadAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cb_AlunoCad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_AlunoCadMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(1, 108, 78));
        jLabel13.setText("Data :");

        jLabel14.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(1, 108, 78));
        jLabel14.setText("Número de Aulas:");

        jLabel15.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(1, 108, 78));
        jLabel15.setText("Número de Faltas:");

        btn_novo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_novo.setForeground(new java.awt.Color(0, 102, 102));
        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_cad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_cad.setForeground(new java.awt.Color(0, 102, 102));
        btn_cad.setText("Cadastrar");
        btn_cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cb_FuncCad, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(cb_TurmaCad, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(147, 147, 147)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cb_AlunoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txt_dataCad, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_aulasCad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txt_FaltasCad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btn_cad, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel5))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_FuncCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_TurmaCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_AlunoCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dataCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_aulasCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_FaltasCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jPanel2);

        lbl_id.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(1, 108, 78));
        lbl_id.setText("----");

        cb_FuncCons.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cb_FuncConsAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(1, 108, 78));
        jLabel17.setText("RA Aluno:");

        jLabel18.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(1, 108, 78));
        jLabel18.setText("Data :");

        jLabel19.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(1, 108, 78));
        jLabel19.setText("Número de Aulas:");

        jLabel20.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(1, 108, 78));
        jLabel20.setText("Número de Faltas:");

        cb_pes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RA", "Data", "Funcionario" }));

        txt_Pes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_PesKeyPressed(evt);
            }
        });

        btn_Pes.setText("Pesquisar");
        btn_Pes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesActionPerformed(evt);
            }
        });

        tbl_presenca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "idChamada", "RA Aluno", "Funcionario", "Data", "Aulas Dadas", "Faltas"
            }
        ));
        tbl_presenca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_presencaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_presenca);

        btn_alterar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_alterar.setForeground(new java.awt.Color(0, 102, 102));
        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_excluir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_excluir.setForeground(new java.awt.Color(0, 102, 102));
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(1, 108, 78));
        jLabel40.setText("Funcionário:");

        jLabel41.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(1, 108, 78));
        jLabel41.setText("id:");

        txt_RAAluno.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(cb_pes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txt_Pes, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btn_Pes))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel41)
                .addGap(46, 46, 46)
                .addComponent(jLabel40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(cb_FuncCons, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel17)
                .addGap(142, 142, 142)
                .addComponent(jLabel18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(txt_RAAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txt_dataCons, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel19)
                .addGap(67, 67, 67)
                .addComponent(jLabel20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(txt_AulaCons, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txt_FaltaCons, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_pes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Pes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Pes))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addComponent(jLabel40))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_id)
                    .addComponent(cb_FuncCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_RAAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dataCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_AulaCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_FaltaCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Consulta", jPanel1);

        jLabel21.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(1, 108, 78));
        jLabel21.setText("Até:");

        btn_novo2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_novo2.setForeground(new java.awt.Color(0, 102, 102));
        btn_novo2.setText("Gerar");
        btn_novo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo2ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(1, 108, 78));
        jLabel22.setText("Relatório Completo:");

        jLabel23.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(1, 108, 78));
        jLabel23.setText("Relatório por Aluno:");

        jLabel24.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(1, 108, 78));
        jLabel24.setText("De:");

        btn_novo4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_novo4.setForeground(new java.awt.Color(0, 102, 102));
        btn_novo4.setText("Gerar");
        btn_novo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo4ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(1, 108, 78));
        jLabel25.setText("Relatório por data:");

        jLabel26.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(1, 108, 78));
        jLabel26.setText("RA do aluno:");

        btn_novo5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_novo5.setForeground(new java.awt.Color(0, 102, 102));
        btn_novo5.setText("Gerar");
        btn_novo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo5ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(1, 108, 78));
        jLabel29.setText("e por data:");

        jLabel30.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(1, 108, 78));
        jLabel30.setText("De:");

        jLabel31.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(1, 108, 78));
        jLabel31.setText("Até:");

        btn_novo7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_novo7.setForeground(new java.awt.Color(0, 102, 102));
        btn_novo7.setText("Gerar");
        btn_novo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo7ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(1, 108, 78));
        jLabel32.setText("RA do aluno:");

        jLabel33.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(1, 108, 78));
        jLabel33.setText("Relatório por Aluno");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(16, 16, 16)
                        .addComponent(btn_novo4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(txt_de1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(txt_ate1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(btn_novo5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(txt_RA1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(btn_novo2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel30)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel31))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(69, 69, 69)
                        .addComponent(txt_RA2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txt_de2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txt_ate2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btn_novo7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(btn_novo4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(5, 5, 5)
                        .addComponent(txt_de1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(5, 5, 5)
                        .addComponent(txt_ate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btn_novo5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(5, 5, 5)
                        .addComponent(txt_RA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btn_novo2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_RA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_de2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_novo7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Relatórios", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Cadastro de Chamada");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadActionPerformed
        Presenca a = new Presenca();

        if (txt_dataCad.getDate()==null) {
            JOptionPane.showMessageDialog(null, "Selecione a Data Corretamente");
        } else if (txt_aulasCad.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite a Quantidade de aulas Corretamente");
        }else if (txt_FaltasCad.getText()==null) {
            JOptionPane.showMessageDialog(null, "Digite a Quantidade de Faltas Corretamente");
        } else {
            try {
                java.util.Date F = txt_dataCad.getDate();
                SimpleDateFormat format1 = new SimpleDateFormat("yyyy/MM/dd");
                String datachamada = format1.format(F);

                a.setFuncionario(cb_FuncCad.getSelectedItem().toString());
                a.setTurma(cb_TurmaCad.getSelectedItem().toString());
                a.setRA_Aluno(cb_AlunoCad.getSelectedItem().toString());
                a.setData(datachamada);
                a.setAula(Integer.parseInt(txt_aulasCad.getText()));
                a.setFalta(Integer.parseInt(txt_FaltasCad.getText()));
                
                
            } catch (Exception e) {

            }
            PresencaDAO adao = new PresencaDAO();
            adao.adciona(a);
            JOptionPane.showMessageDialog(null, "Chamada Cadastrada com sucesso");
        }

    }//GEN-LAST:event_btn_cadActionPerformed

    private void cb_FuncCadAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cb_FuncCadAncestorAdded
        FuncionarioDAO tdao = new FuncionarioDAO();
        List<Funcionario> funcionarios = tdao.getLista();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_FuncCad.getModel();
        for (Funcionario funcionario : funcionarios ){
            model.addElement(funcionario.getNome());
        }
    }//GEN-LAST:event_cb_FuncCadAncestorAdded

    private void cb_TurmaCadAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cb_TurmaCadAncestorAdded
        TurmaDAO tdao = new TurmaDAO();
        List<Turma> turmas = tdao.getList();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_TurmaCad.getModel();
        for (Turma turma : turmas ){
            model.addElement(turma.getNome_Turma());
        }
    }//GEN-LAST:event_cb_TurmaCadAncestorAdded

    private void cb_AlunoCadAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cb_AlunoCadAncestorAdded
        cb_AlunoCad.removeAllItems();
        AlunoDAO tdao = new AlunoDAO();
        List<Aluno> alunos = tdao.getListaComTurma(cb_TurmaCad);
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_AlunoCad.getModel();
        for (Aluno aluno : alunos ){
            model.addElement(aluno.getRA());
        }
    }//GEN-LAST:event_cb_AlunoCadAncestorAdded

    private void cb_AlunoCadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_AlunoCadMouseClicked
        cb_AlunoCad.removeAllItems();
        AlunoDAO tdao = new AlunoDAO();
        List<Aluno> alunos = tdao.getListaComTurma(cb_TurmaCad);
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_AlunoCad.getModel();
        for (Aluno aluno : alunos ){
            model.addElement(aluno.getRA());
        }
    }//GEN-LAST:event_cb_AlunoCadMouseClicked

    private void btn_PesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesActionPerformed
        PresencaDAO ldao = new PresencaDAO();
        Presenca l = new Presenca();
        String campo=null;
        if(cb_pes.getSelectedIndex()==0){
            campo="Aluno.RA";
        }else if(cb_pes.getSelectedIndex()==1){
            campo="data_Pres";
        }else if(cb_pes.getSelectedIndex()==2){
            campo="Funcionario.Nome";
        }
        

        ldao.Consultar(campo, txt_Pes.getText(), l);
             
    
  
        
        
        cb_FuncCons.setSelectedItem("" + l.getFuncionario());
        txt_RAAluno.setText(""+l.getRA_Aluno());
        txt_dataCons.setDate(l.getDate());
        txt_AulaCons.setText(""+l.getAula());
        txt_FaltaCons.setText(""+l.getFalta());

        List<Presenca> presencas = ldao.getLista(campo, txt_Pes.getText());
        DefaultTableModel model = (DefaultTableModel) tbl_presenca.getModel();
        model.setNumRows(0);

        for (Presenca presenca : presencas) {
            model.addRow(new Object[]{
                presenca.getIdPresenca(),
                presenca.getRA_Aluno(),
                presenca.getFuncionario(),
                presenca.getDate(),
                presenca.getAula(),
                presenca.getFalta()});
        }
        
    }//GEN-LAST:event_btn_PesActionPerformed

    private void cb_FuncConsAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cb_FuncConsAncestorAdded
        FuncionarioDAO tdao = new FuncionarioDAO();
        List<Funcionario> funcionarios = tdao.getLista();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_FuncCons.getModel();
        for (Funcionario funcionario : funcionarios ){
            model.addElement(funcionario.getNome());
        }
    }//GEN-LAST:event_cb_FuncConsAncestorAdded

    private void tbl_presencaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_presencaMouseClicked
        if (evt.getClickCount() == 1) {
            Integer y=0;
            PresencaDAO ldao = new PresencaDAO();
            cb_FuncCons.setSelectedItem(tbl_presenca.getValueAt(tbl_presenca.getSelectedRow(), 1).toString());
            txt_RAAluno.setText(tbl_presenca.getValueAt(tbl_presenca.getSelectedRow(), 2).toString());
            lbl_id.setText(tbl_presenca.getValueAt(tbl_presenca.getSelectedRow(), 0).toString());
            txt_dataCons.setDate((Date) tbl_presenca.getValueAt(tbl_presenca.getSelectedRow(), 3));
            txt_AulaCons.setText(tbl_presenca.getValueAt(tbl_presenca.getSelectedRow(), 4).toString());
            txt_FaltaCons.setText(tbl_presenca.getValueAt(tbl_presenca.getSelectedRow(), 5).toString());
        }
    }//GEN-LAST:event_tbl_presencaMouseClicked

    private void txt_PesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PesKeyPressed
        btn_PesActionPerformed(null);
    }//GEN-LAST:event_txt_PesKeyPressed

    private void btn_novo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo4ActionPerformed
        PresencaDAO cli = new PresencaDAO();
        cli.gerarRelCompleto();
    }//GEN-LAST:event_btn_novo4ActionPerformed

    private void btn_novo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo5ActionPerformed
        PresencaDAO p = new PresencaDAO();
        p.gerarRelData(txt_de1, txt_ate1);
    }//GEN-LAST:event_btn_novo5ActionPerformed

    private void btn_novo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo2ActionPerformed
        PresencaDAO p = new PresencaDAO();
        p.gerarRelRA(txt_RA1);
    }//GEN-LAST:event_btn_novo2ActionPerformed

    private void btn_novo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo7ActionPerformed
        PresencaDAO p = new PresencaDAO();
        p.gerarRelRAData(txt_RA2,txt_de2,txt_ate2);
    }//GEN-LAST:event_btn_novo7ActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        Presenca a = new Presenca();

        if (txt_dataCons.getDate()==null) {
            JOptionPane.showMessageDialog(null, "Selecione a Data Corretamente");
        } else if (txt_AulaCons.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite a Quantidade de aulas Corretamente");
        }else if (txt_FaltaCons.getText()==null) {
            JOptionPane.showMessageDialog(null, "Digite a Quantidade de Faltas Corretamente");
        } else {
            try {
                java.util.Date F = txt_dataCons.getDate();
                SimpleDateFormat format1 = new SimpleDateFormat("yyyy/MM/dd");
                String datachamada = format1.format(F);

                a.setFuncionario(cb_FuncCons.getSelectedItem().toString());
                a.setRA_Aluno(txt_RAAluno.getText().toString());
                a.setData(datachamada);
                a.setAula(Integer.parseInt(txt_AulaCons.getText()));
                a.setFalta(Integer.parseInt(txt_FaltaCons.getText()));
                
                
            } catch (Exception e) {

            }
            PresencaDAO adao = new PresencaDAO();
            adao.remove(a);
            JOptionPane.showMessageDialog(null, "Chamada Alterada com sucesso");
            btn_PesActionPerformed(evt);
        }
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        Presenca p = new Presenca();
        int r = JOptionPane.showConfirmDialog(null, "Deseja excluir esse registro");
        if (r == 0) {
            p.setIdPresenca(Integer.parseInt(lbl_id.getText()));
            PresencaDAO cdao = new PresencaDAO();
            cdao.remove(p);
            JOptionPane.showMessageDialog(null, "Presença Removida com Sucesso");
            btn_PesActionPerformed(evt);
        }
    }//GEN-LAST:event_btn_excluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Pes;
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_cad;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_novo2;
    private javax.swing.JButton btn_novo4;
    private javax.swing.JButton btn_novo5;
    private javax.swing.JButton btn_novo7;
    private javax.swing.JComboBox cb_AlunoCad;
    private javax.swing.JComboBox cb_FuncCad;
    private javax.swing.JComboBox cb_FuncCons;
    private javax.swing.JComboBox cb_TurmaCad;
    private javax.swing.JComboBox cb_pes;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JTable tbl_presenca;
    private javax.swing.JTextField txt_AulaCons;
    private javax.swing.JTextField txt_FaltaCons;
    private javax.swing.JTextField txt_FaltasCad;
    private javax.swing.JTextField txt_Pes;
    private javax.swing.JTextField txt_RA1;
    private javax.swing.JTextField txt_RA2;
    private javax.swing.JTextField txt_RAAluno;
    private com.toedter.calendar.JDateChooser txt_ate1;
    private com.toedter.calendar.JDateChooser txt_ate2;
    private javax.swing.JTextField txt_aulasCad;
    private com.toedter.calendar.JDateChooser txt_dataCad;
    private com.toedter.calendar.JDateChooser txt_dataCons;
    private com.toedter.calendar.JDateChooser txt_de1;
    private com.toedter.calendar.JDateChooser txt_de2;
    // End of variables declaration//GEN-END:variables
}
